#!/bin/bash

if [ $# -eq 0 ]
then
    ls -l /tmp/hourlyLoggingActive
    exit 0
fi

if [ $1 = "on" ]
then
    touch /tmp/hourlyLoggingActive
    $0
    echo "###### ACTIVATE #############################################" | hlog
    exit 0
fi

if [ $1 = "off" ]
then
    echo "#### DEACTIVATE #############################################" | hlog
    rm -f /tmp/hourlyLoggingActive
    $0
    exit 0
fi

echo Args not understood: $@
exit 1

