#!/bin/sh
# my home site without having to ftp during the day.
# Ted Park, August, 1994.
#SPOOLDIR="/usr/spool/news/clari/feature/dilbert"
SPOOLDIR="/usr/spool/news/talk/abortion"
if [ -f art_proc ] ; then
 echo "art_proc exists."
else
  echo "No art_proc file."
  touch art_proc
fi
for i in `ls $SPOOLDIR`
do
   echo $i
   if [ -f art_proc ] ; then
      if grep -s $i art_proc ; then
      :
      else
         echo "Now adding to list."
         echo $i >> art_proc
         head  $SPOOLDIR/$i | grep "^From: " | sed -e 's/^From: //' >> poster.list
         head  $SPOOLDIR/$i | grep "^Subject: " | sed -e 's/^Subject: //' >> subject.list
      fi
   else
     echo "No art_proc file."
   fi
done
cat /dev/null > /tmp/file3
cat /dev/null > /tmp/sfile3
FIRSTCOUNT=`cat poster.list | wc -l `
SECONDCOUNT=0
sort -u poster.list > /tmp/file2
sort -u subject.list > /tmp/sfile2
echo "Counting"
cat /tmp/file2 | while read i ; do
  echo $i
  COUNT=`grep "$i" poster.list | wc -l`
  SECONDCOUNT=`echo "$COUNT + $SECONDCOUNT" | bc`
  echo $SECONDCOUNT
  PERCENT=`echo ${COUNT} ${FIRSTCOUNT} | awk '{printf ("scale=6;%d/%d*100\n",$1,$2)}' | bc`
  echo "$COUNT ! $PERCENT ! $i" | awk -F '!' '{printf ("%03d %8.2f%% %s \n", $1, $2, $3)}' >> /tmp/file3
done
echo $FIRSTCOUNT 
echo "Out of $FIRSTCOUNT  articles: " > summary
cat /tmp/file3 | sort -r |  sed -e 's/^00/  /' -e 's/^0/ /' >> summary
SECONDCOUNT=0
cat /tmp/sfile2 | while read i ; do
  echo $i
  COUNT=`grep "$i" subject.list | wc -l`
  SECONDCOUNT=`echo "$COUNT + $SECONDCOUNT" | bc`
  echo $SECONDCOUNT
  PERCENT=`echo ${COUNT} ${FIRSTCOUNT} | awk '{printf ("scale=6;%d/%d*100\n",$1,$2)}' | bc`
  echo "$COUNT ! $PERCENT ! $i" | awk -F '!' '{printf ("%03d %8.2f%% %s \n", $1, $2, $3)}' >> /tmp/sfile3
done
echo $FIRSTCOUNT 
echo "Out of $FIRSTCOUNT  articles: " > ssummary
cat /tmp/sfile3 | sort -r |  sed -e 's/^00/  /' -e 's/^0/ /' >> ssummary
