#!/bin/csh -f
set verbose
cd $HOME/.mail
if ( -f context ) then
    rm context
endif
set MAILDIR=$cwd
touch .dummyFile$$
rm `find . -xdev -type f | fgrep /.`
find . -xdev -type d | sed 's/^\.\///'     >>$MAILDIR/.folders
cd ccur/OSPREY
touch .dummyFile$$
rm `find . -xdev -type f | fgrep /.`
find . -xdev -type d | sed 's/^\./ccur\/OSPREY/' >>$MAILDIR/.folders
cd $MAILDIR
sort -u <$MAILDIR/.folders | fgrep -vx . >$MAILDIR/.folders$$
mv $MAILDIR/.folders$$ $MAILDIR/.folders
