#!/bin/csh -f
set holdFile=/tmp/holdFile$$
foreach f ( $argv )
	echo ""          >>$holdFile && \
	cat $HOME/.mail/inbox/$f >>$holdFile && \
	echo ""          >>$holdFile && \
	rm $HOME/.mail/inbox/$f
end
inc -nosilent -file $holdFile && rm $holdFile
