#!/bin/bash
#
# Try to deal with DHCP-renumberings and other
# network trauma inflicted on us by ComCast.
#

[ -n "$MIKE_DEBUG" ] && set -x

  CHANGED=0
     HOME=/home/mod
     LANG=en_US
 LOCAL_DB=$HOME/currentExternalIPaddr
     PATH=/home/mod/local/script:/home/mod/local/bin.i686:/etc/alternatives:/usr/local/bin:/usr/local/sbin:/usr/bin/mh:/usr/bin:/usr/bin/X11:/usr/games:/usr/sbin:/bin:/sbin:/usr/local:/usr/local/firefox:/usr/local/games:/usr/local/natspeak/bin:/usr/local/share:.
    SHELL=/bin/bash
TIMESTAMP=$(tds)

cd   $HOME
unset IPADDR
unset LAST_KNOWN

# If we can't determine our current external IP address we just write
# a record showing that and then bail out
#
CURRENT_IPADDR=$(currentIPaddr -x)
if [ -z "$CURRENT_IPADDR" ] ; then
    echo "TIMESTAMP=$TIMESTAMP	IPADDR=$CURRENT_IPADDR" >> $LOCAL_DB
    exit 1
fi

# OK, we think we know what our current external IP address
# is so we see if that matches what thought it was the last
# time we thought we had one...
#
x=$(grep -E -e 'IPADDR=[[:digit:]]' currentExternalIPaddr | tail -1)
if [ -n "$x" ] ; then
    LAST_KNOWN=$(eval $x ; echo $IPADDR)
    if [ -z "$LAST_KNOWN" ] ; then                              # Can't happen?
       CHANGED=1
    fi
else
   CHANGED=1
fi

if [ "$CURRENT_IPADDR" != "$LAST_KNOWN" ] ; then
   CHANGED=1
fi

if [ $CHANGED -ne 0 ] ; then
    echo "TIMESTAMP=$TIMESTAMP	IPADDR=$CURRENT_IPADDR" >> $LOCAL_DB
    lftp -e "user michael.odonnell b9lbz4s4tbj4;put $LOCAL_DB -o currentIPaddr;put $LOCAL_DB -o currentIPaddr.txt;put $LOCAL_DB currentExternalIPaddr -o currentIPaddress;put $LOCAL_DB -o currentIPaddress.txt;quit" upload.comcast.net

    for f in currentIPaddr currentIPaddr.txt currentIPaddress currentIPaddress.txt
    do
         cp $LOCAL_DB ~/SYSTEM/b0rken/b0rken-web-root/$f
        scp $LOCAL_DB      b0rken.com:b0rken-web-root/$f
    done
fi

